# Generated by Django 5.1.2 on 2024-10-10 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atenciones_Paramedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atencion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Divisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incendios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('material_utilizado', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigacion_riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo_Avanzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo_Despliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo_Prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo_Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_riesgo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parroquia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('jerarquia', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accidente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_apoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apoyo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cilindro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Incendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incendio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Rescate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rescate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_especiales', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_procedimiento', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_traslado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Accidentes_Transito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_lesionados', models.CharField(max_length=20)),
                ('material_utilizado', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.atenciones_paramedicas')),
                ('tipo_de_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_accidente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Vehiculos_Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('placas', models.CharField(max_length=40)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.accidentes_transito')),
            ],
        ),
        migrations.CreateModel(
            name='Emergencias_Medicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=12)),
                ('idx', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('material_utilizado', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.atenciones_paramedicas')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('placas', models.CharField(max_length=40)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incendios')),
            ],
        ),
        migrations.CreateModel(
            name='Lesionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=12)),
                ('idx', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('id_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.accidentes_transito')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id_tipo_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('id_incendio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incendios')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Presente_Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.evaluacion_riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_externo', models.CharField(default='Interno', max_length=20)),
                ('efectivos_enviados', models.CharField(max_length=40)),
                ('fecha', models.DateField(default='1999-01-01')),
                ('hora', models.TimeField(default='00:00')),
                ('direccion', models.CharField(max_length=50)),
                ('id_division', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.divisiones')),
                ('id_jefe_comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal2', to='web.personal')),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.municipios')),
                ('id_parroquia', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='web.parroquias')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal1', to='web.personal')),
                ('id_tipo_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipos_procedimientos')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Mitigacion_Riesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mitigacion_riesgo')),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.AddField(
            model_name='incendios',
            name='id_procedimientos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
        ),
        migrations.CreateModel(
            name='Guardia_prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_motivo_prevencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_prevencion')),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Falsa_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('motivo_alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_alarma')),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Fallecidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_fallecimiento', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=12)),
                ('edad', models.CharField(max_length=4)),
                ('sexo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion_riesgo',
            name='id_procedimientos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
        ),
        migrations.CreateModel(
            name='Despliegue_Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('motivo_despliegue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_despliegue')),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Atendido_no_Efectuado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.AddField(
            model_name='atenciones_paramedicas',
            name='id_procedimientos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
        ),
        migrations.CreateModel(
            name='Asesoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=12)),
                ('descripcion', models.CharField(max_length=40)),
                ('material_utilizado', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto_Avanzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('id_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_avanzada')),
            ],
        ),
        migrations.CreateModel(
            name='Reinspeccion_Prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=80)),
                ('rif_comercio', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('sexo', models.CharField(max_length=12)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Rescate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('tipo_rescate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_rescate')),
            ],
        ),
        migrations.CreateModel(
            name='Rescate_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('id_rescate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rescate')),
            ],
        ),
        migrations.CreateModel(
            name='Rescate_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('id_rescate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rescate')),
            ],
        ),
        migrations.CreateModel(
            name='Retencion_Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cilindro', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('nro_constancia_retencion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Apoyo_Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_apoyada', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('id_tipo_apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_apoyo')),
            ],
        ),
        migrations.AddField(
            model_name='incendios',
            name='id_tipo_incendio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_incendio'),
        ),
        migrations.CreateModel(
            name='Abastecimiento_agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='Nombre_1 Nombre_2', max_length=40)),
                ('apellidos', models.CharField(default='Apellido_1 Apellido_2', max_length=40)),
                ('cedula', models.CharField(default='V-00000000', max_length=10)),
                ('ltrs_agua', models.CharField(default='0L', max_length=10)),
                ('personas_atendidas', models.CharField(default='0', max_length=10)),
                ('descripcion', models.CharField(default='Aqui va la Descripcion', max_length=40)),
                ('material_utilizado', models.CharField(default='Materiales Usados', max_length=40)),
                ('status', models.CharField(default='...', max_length=20)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('id_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_Especiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_trasladado', models.CharField(max_length=40)),
                ('medico_receptor', models.CharField(max_length=40)),
                ('mpps_cmt', models.CharField(max_length=20)),
                ('id_lesionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.emergencias_medicas')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado_Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_trasladado', models.CharField(max_length=40)),
                ('medico_receptor', models.CharField(max_length=40)),
                ('mpps_cmt', models.CharField(max_length=20)),
                ('id_lesionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.lesionados')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado_Prehospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=12)),
                ('idx', models.CharField(max_length=40)),
                ('hospital_trasladado', models.CharField(max_length=50)),
                ('medico_receptor', models.CharField(max_length=50)),
                ('mpps_cmt', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=120)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('id_tipo_traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipos_traslado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
    ]
