# Generated by Django 5.1.1 on 2024-09-05 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.personal'),
            preserve_default=False,
        ),
    ]
