# Generated by Django 5.1.1 on 2024-09-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_usuarios_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
            ],
        ),
    ]
