# Generated by Django 5.1.1 on 2024-09-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_divisiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parroquia', models.CharField(max_length=40)),
            ],
        ),
    ]
