# Generated by Django 5.1.1 on 2024-09-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_municipios_parroquias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_procedimiento', models.CharField(max_length=40)),
            ],
        ),
    ]
