# Generated by Django 5.1.1 on 2024-09-06 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_tipos_procedimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=40)),
                ('unidad', models.CharField(max_length=40)),
                ('jefe_comision', models.CharField(max_length=40)),
                ('efectivos_enviados', models.CharField(max_length=40)),
                ('hora', models.DateTimeField()),
                ('fecha', models.DateTimeField()),
                ('direccion', models.CharField(max_length=50)),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.municipios')),
                ('id_parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.parroquias')),
                ('id_tipo_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipos_procedimientos')),
            ],
        ),
    ]
