# Generated by Django 5.1.2 on 2024-10-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_asesoramiento_nombre_comercio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspeccion_prevencion',
            name='nombre_comercio',
            field=models.CharField(max_length=80),
        ),
    ]
