# Generated by Django 5.1.2 on 2024-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_reinspeccion_prevencion_nombre_comercio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_riesgo',
            name='tipo_estructura',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
