# Generated by Django 5.1.1 on 2024-09-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_procedimientos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimientos',
            old_name='fecha',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='procedimientos',
            name='hora',
        ),
    ]
