# Generated by Django 5.1.2 on 2024-10-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_evaluacion_riesgo_tipo_estructura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_Artificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artificios_Pirotecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=60)),
                ('rif_comerciante', models.CharField(max_length=60)),
                ('id_fallecido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.fallecidos')),
                ('id_incendio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.incendios')),
                ('id_lesionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.lesionados')),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('tipo_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipos_artificios')),
            ],
        ),
    ]
