# Generated by Django 5.1.2 on 2024-10-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_tipos_artificios_artificios_pirotecnicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artificios_pirotecnicos',
            name='id_fallecido',
        ),
        migrations.RemoveField(
            model_name='artificios_pirotecnicos',
            name='id_incendio',
        ),
        migrations.RemoveField(
            model_name='artificios_pirotecnicos',
            name='id_lesionado',
        ),
        migrations.CreateModel(
            name='Fallecidos_Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_fallecimiento', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=12)),
                ('edad', models.CharField(max_length=4)),
                ('sexo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.artificios_pirotecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='Incendios_Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('material_utilizado', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.artificios_pirotecnicos')),
                ('id_tipo_incendio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_incendio')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Vehiculos_Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('placas', models.CharField(max_length=40)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incendios_art')),
            ],
        ),
        migrations.CreateModel(
            name='Lesionados_Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=12)),
                ('idx', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('id_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.artificios_pirotecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Presente_Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('id_incendio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incendios_art')),
            ],
        ),
    ]
