# Generated by Django 5.1.2 on 2024-10-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_artificios_pirotecnicos_id_fallecido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionados_art',
            name='status',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
