# Generated by Django 5.1.1 on 2024-09-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_personal2_procedimientos_id_jefe_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientos',
            name='id_jefe_comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal2', to='web.personal'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal1', to='web.personal'),
        ),
        migrations.DeleteModel(
            name='Personal2',
        ),
    ]
