# Generated by Django 5.1.1 on 2024-09-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_procedimientos_id_jefe_comision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimientos',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='fecha',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='hora',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='id_division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.divisiones'),
        ),
    ]
