# Generated by Django 5.1.2 on 2024-10-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_lesionados_art_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion_Establecimiento_Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=60)),
                ('rif_comercio', models.CharField(max_length=60)),
                ('encargado_nombre', models.CharField(max_length=60)),
                ('encargado_apellidos', models.CharField(max_length=60)),
                ('encargado_cedula', models.CharField(max_length=60)),
                ('encargado_sexo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('material_utilizado', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('id_proc_artificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
    ]
