# Generated by Django 5.1.1 on 2024-09-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_procedimientos_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientos',
            name='id_parroquia',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='web.parroquias'),
        ),
    ]
