# Generated by Django 5.1.2 on 2024-10-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_tipos_procedimientos_tipo_procedimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='dependencia',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='id_division',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='web.divisiones'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='id_jefe_comision',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal2', to='web.personal'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='id_solicitante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal1', to='web.personal'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='solicitante_externo',
            field=models.CharField(blank=True, default='Interno', max_length=20),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='unidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.unidades'),
        ),
    ]
