# Generated by Django 5.1.1 on 2024-09-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_abastecimiento_agua'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='apellidos',
            field=models.CharField(default='Apellido_1 Apellido_2', max_length=40),
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='cedula',
            field=models.CharField(default='V-00000000', max_length=10),
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='descripcion',
            field=models.CharField(default='Aqui va la Descripcion', max_length=40),
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='ltrs_agua',
            field=models.CharField(default='0L', max_length=10),
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='material_utilizado',
            field=models.CharField(default='Materiales Usados', max_length=40),
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='nombres',
            field=models.CharField(default='Nombre_1 Nombre_2', max_length=40),
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='personas_atendidas',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='status',
            field=models.CharField(default='...', max_length=20),
        ),
    ]
