# Generated by Django 5.1.1 on 2024-09-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_abastecimiento_agua_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoyo_Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apoyo', models.CharField(max_length=50)),
                ('unidad_apoyo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
    ]
