# Generated by Django 5.1.1 on 2024-09-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_apoyo_unidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoyo_unidades',
            old_name='unidad_apoyo',
            new_name='unidad_apoyada',
        ),
    ]
