# Generated by Django 5.1.2 on 2024-10-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_procedimientos_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientos',
            name='id_jefe_comision',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personal2', to='web.personal'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='id_parroquia',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='web.parroquias'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='id_solicitante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personal1', to='web.personal'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.unidades'),
        ),
    ]
