# Generated by Django 5.1.1 on 2024-09-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_rename_unidad_apoyo_apoyo_unidades_unidad_apoyada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia_prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_prevencion', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
    ]
