# Generated by Django 5.1.2 on 2024-10-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_procedimientos_id_jefe_comision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='dependencia',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
