# Generated by Django 5.1.1 on 2024-09-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_guardia_prevencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='abastecimiento_agua',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='abastecimiento_agua',
            name='id_tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.tipo_institucion'),
        ),
    ]
