# Generated by Django 5.1.1 on 2024-09-17 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_tipo_institucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_apoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apoyo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='abastecimiento_agua',
            name='id_tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_institucion'),
        ),
        migrations.AlterField(
            model_name='tipo_institucion',
            name='nombre_institucion',
            field=models.CharField(max_length=50),
        ),
    ]
