# Generated by Django 5.1.2 on 2024-10-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_detalles_enfermeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos_Psicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=12)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=120)),
                ('material_utilizado', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=15)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
    ]
