# Generated by Django 5.1.1 on 2024-09-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_tipo_apoyo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoyo_unidades',
            name='tipo_apoyo',
        ),
        migrations.AddField(
            model_name='apoyo_unidades',
            name='id_tipo_apoyo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.tipo_apoyo'),
            preserve_default=False,
        ),
    ]
