# Generated by Django 5.1.1 on 2024-09-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_apoyo_unidades_tipo_apoyo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_Prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='guardia_prevencion',
            name='motivo_prevencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_prevencion'),
        ),
    ]
