# Generated by Django 5.1.1 on 2024-09-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_motivo_prevencion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardia_prevencion',
            old_name='motivo_prevencion',
            new_name='id_motivo_prevencion',
        ),
    ]
