# Generated by Django 5.1.1 on 2024-09-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_rename_motivo_prevencion_guardia_prevencion_id_motivo_prevencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendido_no_Efectuado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
    ]
