# Generated by Django 5.1.2 on 2024-10-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_procedimientos_capacitacion_id_procedimientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientos',
            name='id_parroquia',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='web.parroquias'),
        ),
        migrations.AlterField(
            model_name='reinspeccion_prevencion',
            name='nombre_comercio',
            field=models.CharField(max_length=40),
        ),
    ]
