# Generated by Django 5.1.1 on 2024-09-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_atendido_no_efectuado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_Despliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Despliegue_Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('motivo_despliegue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_despliegue')),
            ],
        ),
    ]
