# Generated by Django 5.1.2 on 2024-10-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_jornada_medica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inspeccion', models.CharField(max_length=80)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion_Prevencion_Asesorias_Tecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=80)),
                ('propietario', models.CharField(max_length=100)),
                ('cedula_propietario', models.CharField(max_length=12)),
                ('descripcion', models.CharField(max_length=200)),
                ('persona_sitio_nombre', models.CharField(max_length=40)),
                ('persona_sitio_apellido', models.CharField(max_length=40)),
                ('persona_sitio_cedula', models.CharField(max_length=12)),
                ('persona_sitio_telefono', models.CharField(max_length=20)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.inspecciones')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion_Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especifique', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
                ('persona_sitio_nombre', models.CharField(max_length=40)),
                ('persona_sitio_apellido', models.CharField(max_length=40)),
                ('persona_sitio_cedula', models.CharField(max_length=12)),
                ('persona_sitio_telefono', models.CharField(max_length=20)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.inspecciones')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion_Habitabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('persona_sitio_nombre', models.CharField(max_length=40)),
                ('persona_sitio_apellido', models.CharField(max_length=40)),
                ('persona_sitio_cedula', models.CharField(max_length=12)),
                ('persona_sitio_telefono', models.CharField(max_length=20)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.inspecciones')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion_Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('altura_aprox', models.CharField(max_length=40)),
                ('ubicacion_arbol', models.CharField(max_length=100)),
                ('persona_sitio_nombre', models.CharField(max_length=40)),
                ('persona_sitio_apellido', models.CharField(max_length=40)),
                ('persona_sitio_cedula', models.CharField(max_length=12)),
                ('persona_sitio_telefono', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.inspecciones')),
            ],
        ),
    ]
