# Generated by Django 5.1.1 on 2024-09-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_accidentes_transito_atenciones_paramedicas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_especiales', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_Especiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_servicios')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicios_Espaciales',
        ),
    ]
