# Generated by Django 5.1.2 on 2024-10-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_inspecciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion_habitabilidad',
            name='id_inspeccion',
        ),
        migrations.RemoveField(
            model_name='inspeccion_prevencion_asesorias_tecnicas',
            name='id_inspeccion',
        ),
        migrations.RemoveField(
            model_name='inspeccion_arbol',
            name='id_inspeccion',
        ),
        migrations.RemoveField(
            model_name='inspeccion_otros',
            name='id_inspeccion',
        ),
        migrations.AddField(
            model_name='inspeccion_arbol',
            name='id_procedimientos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion_arbol',
            name='tipo_inspeccion',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion_habitabilidad',
            name='id_procedimientos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion_habitabilidad',
            name='tipo_inspeccion',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion_otros',
            name='id_procedimientos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion_otros',
            name='tipo_inspeccion',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion_prevencion_asesorias_tecnicas',
            name='id_procedimientos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion_prevencion_asesorias_tecnicas',
            name='tipo_inspeccion',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inspecciones',
        ),
    ]
