# Generated by Django 5.1.1 on 2024-09-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_tipo_servicios_servicios_especiales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='falsa_alarma',
            name='motivo_alarma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_alarma'),
        ),
    ]
