# Generated by Django 5.1.1 on 2024-09-20 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_motivo_alarma_alter_falsa_alarma_motivo_alarma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('placas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Incendios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('material_utilizado', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('id_incendio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incendios')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Incendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incendio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Detalles_vehiculo',
        ),
        migrations.AddField(
            model_name='detalles_vehiculos',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incendios'),
        ),
        migrations.AddField(
            model_name='incendios',
            name='id_tipo_incendio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_incendio'),
        ),
    ]
