# Generated by Django 5.1.1 on 2024-09-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_detalles_vehiculos_incendios_persona_presente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accidente', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_trasladado', models.CharField(max_length=40)),
                ('medico_receptor', models.CharField(max_length=40)),
                ('mpps_cmt', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='accidentes_transito',
            name='cantidad_lesionados',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accidentes_transito',
            name='id_atencion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.atenciones_paramedicas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atenciones_paramedicas',
            name='id_procedimientos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atenciones_paramedicas',
            name='material_utilizado',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atenciones_paramedicas',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atenciones_paramedicas',
            name='tipo_atencion',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='apellidos',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='cedula',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='descripcion',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='edad',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='id_accidente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.accidentes_transito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='idx',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='nombres',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='sexo',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Detalles_Vehiculos_Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('placas', models.CharField(max_length=40)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.accidentes_transito')),
            ],
        ),
        migrations.CreateModel(
            name='Emergencias_Medicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=12)),
                ('idx', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.atenciones_paramedicas')),
            ],
        ),
        migrations.AddField(
            model_name='accidentes_transito',
            name='tipo_de_accidente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.tipo_accidente'),
            preserve_default=False,
        ),
    ]
