# Generated by Django 5.1.2 on 2024-10-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_personal2_alter_procedimientos_id_jefe_comision_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal2',
        ),
    ]
