# Generated by Django 5.1.1 on 2024-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_traslado_id_lesionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atenciones_paramedicas',
            name='material_utilizado',
        ),
        migrations.RemoveField(
            model_name='atenciones_paramedicas',
            name='status',
        ),
        migrations.AddField(
            model_name='accidentes_transito',
            name='material_utilizado',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accidentes_transito',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencias_medicas',
            name='material_utilizado',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencias_medicas',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionados',
            name='status',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atenciones_paramedicas',
            name='tipo_atencion',
            field=models.CharField(max_length=30),
        ),
    ]
