# Generated by Django 5.1.2 on 2024-10-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_delete_personal2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('jerarquia', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
    ]
