# Generated by Django 5.1.2 on 2024-10-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_personal2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal2',
        ),
    ]
