# Generated by Django 5.1.1 on 2024-09-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_remove_atenciones_paramedicas_material_utilizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesionados',
            name='status',
        ),
    ]
