# Generated by Django 5.1.2 on 2024-10-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_delete_personal2'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cedula',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='sexo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
