# Generated by Django 5.1.1 on 2024-09-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_remove_lesionados_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_riesgo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('id_tipo_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_riesgo')),
            ],
        ),
    ]
