# Generated by Django 5.1.2 on 2024-10-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_personal_cedula_personal_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='rol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
