# Generated by Django 5.1.2 on 2024-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_personal_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
