# Generated by Django 5.1.1 on 2024-09-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_mitigacion_riesgo_mitigacion_riesgos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimientos',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='mitigacion_riesgos',
            name='id_tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mitigacion_riesgo'),
        ),
    ]
