# Generated by Django 5.1.1 on 2024-09-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_remove_procedimientos_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='unidad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.unidades'),
            preserve_default=False,
        ),
    ]
