# Generated by Django 5.1.1 on 2024-09-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_procedimientos_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_Avanzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto_Avanzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('id_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.motivo_avanzada')),
            ],
        ),
    ]
