# Generated by Django 5.1.1 on 2024-09-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_motivo_avanzada_puesto_avanzada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_traslado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Traslado_Prehospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=12)),
                ('idx', models.CharField(max_length=40)),
                ('hospital_trasladado', models.CharField(max_length=50)),
                ('medico_receptor', models.CharField(max_length=50)),
                ('mpps_cmt', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=120)),
                ('material_utilizado', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
                ('id_tipo_traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipos_traslado')),
            ],
        ),
    ]
