# Generated by Django 5.1.1 on 2024-09-26 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_reinspeccion_prevencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retencion_Preventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cilindro', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('nro_constancia_retencion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('material_utilizado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
    ]
