# Generated by Django 5.1.1 on 2024-10-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_tipo_cilindro'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='solicitante_externo',
            field=models.CharField(default='Interno', max_length=20),
        ),
    ]
